[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vlcr"
version = "0.1.0"
dependencies = ["audio-metadata"]

[project.scripts]
vlcr = "vlcr.main:main"